export const USER_TAG = 'USER_TAG'
export const PROFILE_TAG = 'PROFILE_TAG'
export const POST_TAG = 'POST_TAG'
export const VIEWER_TAG = 'VIEWER_TAG'
export const SUBSCRIPTION_TAG = 'SUBSCRIPTION_TAG'
