export { PostDetails } from './ui/PostDetails/PostDetails'
export { PostDetailsCardSkeleton } from './ui/PostDetailsCard/PostDetailsCard'
export { setUpdatedPostList, postDetailsReducer } from './model/slice/postDetailsSlice'
export { PostDetailsVariant } from './model/consts/variant'
export type { PostDetailsSchema } from './model/types/postDetailsSchema'
