export { SignUp } from './ui/signup'
export { SignUpModal } from './ui/modalWindow/ui/SignUpModal'
export { MergeAccount } from './ui/SignUpAdditionPages/ui/MergeAccount/ui/MergeAccount'
export { Congratulation } from './ui/SignUpAdditionPages/ui/Congratulation/ui/Congratulation'
export { Verification } from './ui/SignUpAdditionPages/ui/Verification/ui/Verification'
